spring:
    data:
        mongodb:
            database: ${MONGO_DATABASE:iot} 
            port: ${MONGO_PORT:27017} 
            host: ${MONGO_HOST:localhost}
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
server:
    port: ${DATA_SERVICE_PORT:8082} 
broker:
    uri: ${BROKER_URL:tcp://localhost:1883}
    clientId: ${BROKER_CLIENT_ID:serviceMessageClient}
    topic: ${BROKER_TOPIC:device_messages}